name: Example Workflow

on:
  workflow_dispatch:
    inputs:
      ignore_endo_branch:
        description: 'Ignore Endo Branch'
        required: true
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IGNORE_DIRTY_YARN_LOCK: ${{ inputs.ignore_endo_branch == 'false' && 'true' || 'false' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Printing
        run: |
          echo "IGNORE_DIRTY_YARN_LOCK is set to $IGNORE_DIRTY_YARN_LOCK"
          echo "Input ignore_endo_branch is ${{ inputs.ignore_endo_branch }}"
          if [ "$IGNORE_DIRTY_YARN_LOCK" = true ]; then
            echo "If Condition RAN" 
          fi


      # - name: Get the appropriate Endo branch
      #   id: endo-branch
      #   uses: actions/github-script@v7
      #   with:
      #     result-encoding: string
      #     script: |-
      #       echo ${{ inputs.ignore-endo-branch }}
      #       if (${{ inputs.ignore-endo-branch }}) {
      #         echo RANNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
      #       }
